### ISSUE TITLE
Webpack unable to compile due to export `default` not last

### ISSUE THREAD

**Issue by erawk** [prisma/extension-read-replicas#19]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂 It's so nice to see read replica support in Prisma.

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@prisma/extension-read-replicas@0.2.2` for the project I'm working on.

When adding this read replica extension to my NextJS project, I encountered an error: https://nextjs.org/docs/messages/module-not-found. Our build would not compile.

The core issue is that the `default` key in the `exports` in `package.json` is expected to be _last_. 

I've seen this before, with Firebase: https://github.com/firebase/firebase-js-sdk/issues/7002#issuecomment-1414526580

The solve here was easy, just reordering the `package.json` to have the `default` key last.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@prisma/extension-read-replicas/package.json b/node_modules/@prisma/extension-read-replicas/package.json
index db6d064..780eedd 100644
--- a/node_modules/@prisma/extension-read-replicas/package.json
+++ b/node_modules/@prisma/extension-read-replicas/package.json
@@ -17,12 +17,12 @@
   "exports": {
     ".": {
       "require": {
-        "default": "./dist/index.js",
-        "types": "./dist/index.d.ts"
+        "types": "./dist/index.d.ts",
+        "default": "./dist/index.js"
       },
       "import": {
-        "default": "./dist/index.mjs",
-        "types": "./dist/index.d.mts"
+        "types": "./dist/index.d.mts",
+        "default": "./dist/index.mjs"
       }
     }
   },
```

After applying this with `patch-package`, my builds succeeded as expected.
```[tasklist]
### Tasks
```

**Comment by nick-cheatwood7** [comment]
@erawk,

I was also facing this, but was also able to resolve this using `pnpm patch`.  Thank you for sharing 🎉!

[See `pnpm patch` docs](https://pnpm.io/cli/patch)

**Comment by mwskwong** [comment]
I was not expecting this issue to be left unhandled for this long, especially when the fix is quite straightforward. Opened a PR for this.
