### ISSUE TITLE
Unable to add options for replica client constructors

### ISSUE THREAD

**Issue by casey-chow** [prisma/extension-read-replicas#20]
I need to add logging to our read replica clients, but the client does not allow me to adjust constructor queries.

https://github.com/prisma/extension-read-replicas/blob/3c1a7127b4c80a3352893d8bea71c73898d8d391/src/ReplicaManager.ts#L23C26-L25

**Comment by janpio** [comment]
Very good point. Would you expect the replica Clients to inherit the configuration from the main Client, or do you want to customize it somehow when activating the extension?

**Comment by casey-chow** [comment]
Personally I'd expect it to inherit the configuration, but it's easy to argue it's better to just allow user-level customization.

**Comment by yicrotkd** [comment]
I've submitted a pull request to address this issue. I would appreciate it if you could review and confirm. Thank you!

**Comment by pciruzzi** [comment]
@erawk @SevInf @janpio Hey, I've came across this issue too. Do you intend to release the PR soon? 🙂
