### ISSUE TITLE
Documentation - How does the normal/write instance's URL mentioned for the PrismaClient

### ISSUE THREAD

**Issue by KrishnaPravin** [prisma/extension-read-replicas#33]
In this section of the documentation, the normal/write instance's URL is not mentioned. https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/read-replicas#setup-the-read-replicas-extension.

Is the URL in the `prisma.schema` file is itself sufficient ?

**Comment by SevInf** [comment]
@KrishnaPravin, yes, url from schema file is the primary URL.
